1 SCREEN 1
2 COLOR 1, 1
10 PRINT " |\"
11 PRINT " | \"
12 PRINT " |  \"
14 PRINT " |   \"
15 PRINT " |____\_________________________"
16 PRINT " / _          _          _ |____\"
17 PRINT "| | |[][][][]| |[][][][]| |      \"
18 PRINT "----------------------------------"
19 PRINT "   |                      /"
20 PRINT "   |                    /"
21 PRINT "   |                  /"
22 PRINT "   |                /"
23 PRINT "   |              /"
24 PRINT "   |            /"
25 PRINT "   |          /"
26 PRINT "   |        /"
27 PRINT "   |      /"
28 PRINT "   |    /"
29 PRINT "   |  /"
30 PRINT "   |/"
31 PRINT "GGITKO AIR (GGAIR).CALLSIGN:GGAIR"
32 PRINT "GGITKO CO. INC. "
33 PRINT "#STAYHOME"
34 PRINT "PRESS ANY KEY TO CONTINUE"
35 A$ = INPUT$(1)
36 END
                                    

